import type { Metadata } from 'next';
import { Raleway } from 'next/font/google';
import Provider from './components/Provider';
const raleway = Raleway({ subsets: ['latin'], weight: '500' });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body className={raleway.className}><Provider>{children}</Provider></body>
    </html>
  );
}
